server:
  port: 22345

mybatis-plus:
  type-aliases-package: com.gton.user.entity
  mapper-locations: classpath*:com/gton/user/mapper/xml/*Mapper.xml,classpath*:/mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true  #开启驼峰命名
#    cache-enabled: false #开启二级缓存
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台日志
  check-config-location: true # 检查xml是否存在
  type-enums-package: com.gton.enumPackage  #通用枚举开启
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-field: isDel
      logic-delete-value: 0

logging:
  level:
    cn.camio1945: warn
    com.baomidou.mybatisplus.core.executor.BaseExecutor: warn
    com.clickhouse: error

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:clickhouse://192.168.0.39:8123/order_bottleneck_test
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    username: default
    password: clickhouse

