server:
  port: 22345

# 如果开启，则会在控制台打印出 mybatis 的 sql 语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.camio1945: warn
    com.baomidou.mybatisplus.core.executor.BaseExecutor: warn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_bottleneck_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: order_bottleneck_test
    password: Wng7_fncoia__2er
    hikari:
      maximum-pool-size: 20
