server:
  port: 22345

# 如果开启，则会在控制台打印出 mybatis 的 sql 语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.camio1945: warn
    com.baomidou.mybatisplus.core.executor.BaseExecutor: warn

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/order_bottleneck_test
    driver-class-name: org.postgresql.Driver
    username: order_bottleneck_test
    password: Wng7_fncoia__2er
    hikari:
      maximum-pool-size: 20
