server:
  port: 22345

# 如果开启，则会在控制台打印出 mybatis 的 sql 语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.camio1945: warn
    com.baomidou.mybatisplus.core.executor.BaseExecutor: warn

spring:
  datasource:
    url: jdbc:mysql://192.168.0.199:4000/order_bottleneck_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: order_bottleneck_test
    password: Wng7_fncoia__2er
    hikari:
      maximum-pool-size: 20
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      timeout: 10000ms
      host: 172.20.2.103
      port: 6379
      password:
      database: "6"
  cache:
    type: redis
    redis:
      cache-null-values: true
      # 单位为分钟，在 RedisConfig.java 中用到
      time-to-live: 1440
