DROP TABLE IF EXISTS "public"."goods";
DROP TABLE IF EXISTS "public"."order";
DROP TABLE IF EXISTS "public"."order_item";
DROP TABLE IF EXISTS "private"."goods";
DROP TABLE IF EXISTS "private"."order";
DROP TABLE IF EXISTS "private"."order_item";
DROP SCHEMA IF EXISTS "public";
DROP SCHEMA IF EXISTS "private";
DROP DATABASE IF EXISTS order_bottleneck_test;
DROP ROLE IF EXISTS order_bottleneck_test;
CREATE DATABASE order_bottleneck_test ENCODING 'UTF8';
CREATE ROLE order_bottleneck_test LOGIN PASSWORD 'Wng7_fncoia__2er';
\c order_bottleneck_test
CREATE SCHEMA "private" AUTHORIZATION "order_bottleneck_test";
GRANT CREATE ON SCHEMA "private" TO order_bottleneck_test;

DROP TABLE IF EXISTS "private"."goods";
CREATE TABLE "private"."goods" (
  "id" int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "price" numeric(8,2) NOT NULL,
  "stock" int4 NOT NULL,
  "is_on" int2 NOT NULL,
  "first_img" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "intro" text COLLATE "pg_catalog"."default",
  "add_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "private"."goods"."id" IS '主键';
COMMENT ON COLUMN "private"."goods"."name" IS '名称';
COMMENT ON COLUMN "private"."goods"."price" IS '价格';
COMMENT ON COLUMN "private"."goods"."stock" IS '库存';
COMMENT ON COLUMN "private"."goods"."is_on" IS '是否上架';
COMMENT ON COLUMN "private"."goods"."first_img" IS '第一张图片';
COMMENT ON COLUMN "private"."goods"."intro" IS '详情';
COMMENT ON COLUMN "private"."goods"."add_time" IS '添加时间';
COMMENT ON TABLE "private"."goods" IS '商品';

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE "private"."goods" TO order_bottleneck_test;

INSERT INTO "private"."goods" VALUES (1, '锤子（smartisan ) 坚果 Pro 2S 6G+64GB 炫光蓝 全面屏双摄 全网通4G手机 双卡双待 游戏手机', 1998.00, 100000001, 1, 'https://resource.smartisan.com/resource/25cc6e783a664fbdf83c3c34774a9826.png', 'https://resource.smartisan.com/resource/25cc6e783a664fbdf83c3c34774a9826.png', '2024-03-14 17:38:13');
INSERT INTO "private"."goods" VALUES (2, '坚果 R2 浅黑色 8G+128G', 2699.00, 100000001, 1, 'https://resource.smartisan.com/resource/4d9e7683b590cf4a6996d3b13136bcf8.png?x-oss-process=image/resize,w_791/format,webp', 'https://resource.smartisan.com/resource/4d9e7683b590cf4a6996d3b13136bcf8.png?x-oss-process=image/resize,w_791/format,webp', '2024-03-14 18:22:53');
INSERT INTO "private"."goods" VALUES (3, 'Smartisan TNT go 有线版', 1199.00, 100000001, 1, 'https://resource.smartisan.com/resource/2d68b229cc7cafbb1e74bc0f996fa57c.png?x-oss-process=image/resize,w_791/format,webp', 'https://resource.smartisan.com/resource/2d68b229cc7cafbb1e74bc0f996fa57c.png?x-oss-process=image/resize,w_791/format,webp', '2024-03-14 18:24:35');
INSERT INTO "private"."goods" VALUES (4, 'Smartisan 手机支架', 39.00, 100000001, 1, 'https://resource.smartisan.com/resource/8b0fe3117164dab7d91439b93dc112e0.png?x-oss-process=image/resize,w_791/format,webp', 'https://resource.smartisan.com/resource/8b0fe3117164dab7d91439b93dc112e0.png?x-oss-process=image/resize,w_791/format,webp', '2024-03-14 18:25:52');
INSERT INTO "private"."goods" VALUES (5, 'Smartisan 智能手写笔', 499.00, 100000001, 1, 'https://resource.smartisan.com/resource/c9a55fe8b5bc506fec60659aa2dcebe9.png?x-oss-process=image/resize,w_791/format,webp', 'https://resource.smartisan.com/resource/c9a55fe8b5bc506fec60659aa2dcebe9.png?x-oss-process=image/resize,w_791/format,webp', '2024-03-14 18:26:32');

CREATE INDEX "is_on" ON "private"."goods" USING btree (
  "is_on" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "price" ON "private"."goods" USING btree (
  "price" "pg_catalog"."numeric_ops" ASC NULLS LAST
);
CREATE INDEX "stock" ON "private"."goods" USING btree (
  "stock" "pg_catalog"."int4_ops" ASC NULLS LAST
);




DROP TABLE IF EXISTS "private"."order";
CREATE TABLE "private"."order" (
  "id" int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sn" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "user_id" int4 NOT NULL,
  "name" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "shipping_mobile" varchar(15) COLLATE "pg_catalog"."default" NOT NULL,
  "shipping_name" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "shipping_detail" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "total_amount" numeric(10,2) NOT NULL,
  "status" int4 NOT NULL,
  "add_time" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "private"."order"."id" IS '主键';
COMMENT ON COLUMN "private"."order"."sn" IS '编号';
COMMENT ON COLUMN "private"."order"."user_id" IS '用户ID';
COMMENT ON COLUMN "private"."order"."name" IS '下单人姓名';
COMMENT ON COLUMN "private"."order"."shipping_mobile" IS '收货地址中的手机号';
COMMENT ON COLUMN "private"."order"."shipping_name" IS '收货地址中的姓名';
COMMENT ON COLUMN "private"."order"."shipping_detail" IS '收货地址';
COMMENT ON COLUMN "private"."order"."total_amount" IS '订单总金额';
COMMENT ON COLUMN "private"."order"."status" IS '状态：1-待支付，2-待发货，3-待收货，4-已完成，5-已取消';
COMMENT ON COLUMN "private"."order"."add_time" IS '下单时间';
COMMENT ON TABLE "private"."order" IS '订单';

CREATE INDEX "addTime" ON "private"."order" USING btree (
  "add_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE INDEX "status" ON "private"."order" USING btree (
  "status" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "unique-sn" ON "private"."order" USING btree (
  "sn" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "user_id" ON "private"."order" USING btree (
  "user_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE "private"."order" TO order_bottleneck_test;



DROP TABLE IF EXISTS "private"."order_item";
CREATE TABLE "private"."order_item" (
  "id" int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int4 NOT NULL,
  "goods_id" int4 NOT NULL,
  "goods_count" int4 NOT NULL,
  "goods_price" numeric(8,2) NOT NULL,
  "goods_img" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "total_amount" numeric(10,2) NOT NULL
)
;
COMMENT ON COLUMN "private"."order_item"."id" IS '主键';
COMMENT ON COLUMN "private"."order_item"."order_id" IS '订单ID';
COMMENT ON COLUMN "private"."order_item"."goods_id" IS '商品ID';
COMMENT ON COLUMN "private"."order_item"."goods_count" IS '商品数量';
COMMENT ON COLUMN "private"."order_item"."goods_price" IS '商品单价';
COMMENT ON COLUMN "private"."order_item"."goods_img" IS '商品图片';
COMMENT ON COLUMN "private"."order_item"."total_amount" IS '单商品总金额';
COMMENT ON TABLE "private"."order_item" IS '订单项';

CREATE INDEX "goods_id" ON "private"."order_item" USING btree (
  "goods_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "order_id" ON "private"."order_item" USING btree (
  "order_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE "private"."order_item" TO order_bottleneck_test;

